local firstString = "hello world"
print(string.len(firstString))
print(string.lower(firstString))
print(string.upper(firstString))
print(string.char(96))
print(string.format("%s", "hello"))
local string2 = string.rep("hi",5)
print(string2)
print(string.sub("testtest",1,3))
print(string.byte("test",1,2,3,4))
print(string.format("pi: %.4f", math.pi))
print(string.format("%02d-%02d-%04d", 12,2,3022))
print(string.match("/v3/user/v4","/v3/user1"))
print(string.match("/v3/user/v4","/v3/user"))
print(not string.find("/v3/user/v4","/v3/user"))
local subString = string.gsub("test","t","n")
print(subString)
